name: museum_search
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2

  drag_and_drop_lists: ^0.3.3
  flutter:
    sdk: flutter

  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.11.0
  flutter_map: ^3.1.0
  flutter_native_splash: ^2.2.16

  flutter_polyline_points: ^1.0.0

  flutter_slidable: ^3.0.0
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0

  geolocator: ^9.0.2

  google_maps_flutter: ^2.2.5

  hooks_riverpod: ^2.3.4

  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  location: ^4.4.0
  mapbox_polyline_points: ^0.0.4
  permission_handler: ^10.2.0
  platform_maps_flutter: ^1.0.2
  url_launcher: ^6.1.10

dev_dependencies:

  build_runner: ^2.3.2
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/numbers/
    - .env
